### ISSUE TITLE
Reflect changes into HubSpot once at end of engine run.

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#39]
### What

Reflect all data changes into HubSpot at the end of a run *only*.

### Why

1. To consolidate API calls
   1. Possibly reduces run time slightly if batches can be combined
   2. Creates opportunity to simplify Entity & EntityManager
      2. If we sync at end, we won't reuse entities at all
         1. During `npm run multiple`, entities are recreated from memory cache
         2. In prod, new entities are recreated from live data each run
      4. Not needing to reuse them means a lot of simplifications possible
         1. But that's a big step that means not being able to upsync *during* engine run again.
         2. *Needs serious consideration.*
   3. Greatly simplifies developer mindset
      1. No need to think about whether an entity has an ID
      2. No need to worry about whether to upsync or not
      3. Create/update entities as needed, however needed
      4. Reflect everything into HubSpot at the end. That's it.
2. To be able to make successive changes
   1. This may reduce API calls and make remote data consistent. For example:
      1. Engine phase 1 sets Contact A to Customer
      2. Engine phase 2 upserts Contact A (type=Customer)
      3. Engine phase 3 gathers more data
      4. Engine phase 4 sets Contact A to Partner
      5. Engine phase 5 upserts Contact A (type=Partner)
      6. This will happen *on every engine run*, causing:
         1. Extra API calls, but more importantly:
         2. Incorrect data in HubSpot for possibly whole minutes

### Technical Considerations

2. Upserting at the end means:
   1. Indexes won't get updated as entity properties are updated
      1. When do we use indexes?
         1. GetById (see 2.2.1.1 below)
            1. We won't be getting by ID if we don't have one yet
         2. Get deals by transactionId/addonLicenseId
            1. We *do* update these during engine run
               1. So we'll need to reindex as these change
         3. Get contacts by email
            1. We use it in bin/scripts
            2. We use it throughout the engine
            3. Do we change allEmails?
               1. We never change contact.email
               2. We never change contact.data.otherEmails
               3. We only use these to *get* contacts (via allEmails)
            4. So apparently not.
            5. But even if we did, we could just update the index
      2. So apparently we do need to update indexes on property changes
         1. When a property is updated on Entity
            1. Check if property has index
               1. Implies Entity has knowledge of indexes
                  1. Probably should move index knowledge into Entity
                     1. Each Entity provides static getters into indexable parts
                     2. Each EntityManager just grabs this in makeIndex
                        1. (Just realized makeIndex should *return* a getter, e.g. `public getByEmail = this.makeIndex(c => c.allEmails)` since that's the only way it's ever used. But maybe not in the future.)
                     3. Then Entity can know its own indexable properties
                        1. But properties are getters right now, e.g.:
                           1. c.allEmails
                           2. [e.id].filter(isPresent)
                           3. d.data.addonLicenseId
                        2. How can we test if our current changing property is an index if this is a getter and not a string?
                           1. Can't use dot-access lib because logic like .filter
                           2. Could just provide an array of properties
                              1. "id" is special-case, we don't need it here
                              2. The array can be checked via get & isPresent
                              3. Problem solved!
            2. If it does, remove its indexes via old property
            3. Then update the property as usual in Entity
            4. Then update the indexes via new property
            5. Voila!
   2. IDs won't necessarily exist for any given entity during engine run.
      1. Do we ever expect IDs to exist?
         1. EntityManager assumes it for GetById
            1. Bin-scripts use it with cached data (definitely exists)
            2. Database uses it to get entity by id
               1. Only used by Entity when fetching associated entities
                  1. This is literally what we're changing :thumbsup:
         2. Entity uses it for associations
            1. This is literally what we're changing :thumbsup:
         3. Bin-scripts use it using cached data (definitely exists)
         4. Engine uses it when printing duplicate deals (before generating new ones, so ID exists)
         5. Engine uses it to log that no properties needed to be updated for a given deal (technically may not exist since it's gotten by addonLicenseId or transactionId indexes, but happens before deal generation so always exists)
         6. Therefore we can safely run engine on many ID-less entities
            1. New code must assume entity may not have ID.
            2. But I mean, like, reasonably... E.g. printing duplicate deals can.
   3. Associations will need to be entities instead of strings.
      1. Database will have to link all entities together *after* downloading *all* types.
         1. Will need to store raw-associations in each EntityManager
         2. Will have to loop through each and add each entity to each entity
            1. Associating them after download will use the same internal mechanics as associating them as normal entity-using code
         3. Adding/removing/clearing associations will be Set operations :party:
            1. They'll have to be done in reverse direction also (see above)
         4. Associations should probably be done in both directions
            1. This adds consistency and predictability for developer usage
            2. They'll have to be upserted in only one direction
               1. We can probably just add this as metadata in EntityManager.associations

### Tasks:

- [x] Make associations use real entities
- [x] Make associations automatically two-way
- [x] Upsync associations in one direction only
- [x] Ensure we can safely do everything we want with ID-less entities
- [x] Update entity indexes as their properties change

**Comment by bberenberg** [comment]
Another reason for "Why" is to decouple the engine from the uploader so others can add their own destinations more easily in the future.

**Comment by sdegutis** [comment]
@bberenberg I think that's independent of this task and can be done with the current code pretty easily.

Technical details (for future reference):

1. Abstract HubspotService into CrmService
2. Rename variables everywhere accordingly
3. Implement CrmService with another (e.g. SalesForceService)
4. Refactor interface into LCD of each service as needed
5. Adjust EntityManager as needed due to any interface changes

**Comment by sdegutis** [comment]
After this task is done (it's 4/5 now), we'll have a non-urgent cleanup task of cleaning up the clearly duplicated and scattered information between Entity and EntityManager:

1. Kind name should go on each subclass like Deal. This is already kind of doable but requires a weird hack of doing `(this.constructor as any).kind` to get the kind at the subclass instance level.
2. Association properties are repeated on EntityManager subclasses between up and down, because I wanted to put them in a mapped type but those don't work for enums. But this might be cleaned up with the following task:
3. Associations are sort of scattered between Entity instances, Entity subclasses, and EntityManager instances. I think this can be combined into something on Entity subclasses, accessible by both Entity instances and EntityManager instances.

These aren't long tasks, they just need a little more thought to do them right, and they're not urgent (the code works as-is and is relatively clean, just, could be easier to work with).
